spring:
  devtools:
    restart:
      enabled: 'true'
    livereload:
      enabled: 'true'
  datasource:
    url: jdbc:postgresql://localhost:5432/basicdb
    username: dikalee
    password: d09209233!
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        "[format_sql]": true
        "[default_batch_fetch_size]": 1000 #최적화 옵션
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

logging.level:
  root: info
  '[myone.apijpa]': debug
  '[org.hibernate.SQL]': debug
  '[org.hibernate.type]': trace

