spring:
  devtools:
    restart:
      enabled: 'true'
    livereload:
      enabled: 'true'
  datasource:
    url: ENC(+WBVIYuofWzJNpo3a1xmOdjDWeQLNdSyrT1hQN2C74gRUe5MK/kflrbGVt1ur3UPm7l1JjItgog=)
    username: ENC(cwRDmf16XqXutkGk6Ld+DA==)
    password: ENC(DvaSrXsme1EV77m+X/ncxeS2w51NoWiD)
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        "[format_sql]": true
        "[default_batch_fetch_size]": 1000 #최적화 옵션
        "[use_sql_comments]": true;
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

logging.level:
  root: info
  '[myone.apijpa]': debug
  '[org.hibernate.SQL]': debug
#  '[org.hibernate.type]': trace

